import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// const inter = Roboto({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ['latin'],weight: ['400', '700'],style: ['normal', 'italic']});
 // weight: ['400', '700'], // You can specify different weights if needed
  // style: ['normal', 'italic'], // Optional: You can include styles if necessary

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
